/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "main.h"

int main(void) {
	SSD1306_Config_t config = ws_sys_start();

	ssd1306_clear_screen(config.pGPIOConfiguration, config.pSPIConfiguration, 0xFF);
	_delay_ms(1000);
	ssd1306_clear_screen(config.pGPIOConfiguration, config.pSPIConfiguration, 0x00);
	ssd1306_display_string(config.pGPIOConfiguration, config.pSPIConfiguration, 18, 0, (uint8_t*) "1.3inch OLED", 16, 1);
	ssd1306_display_string(config.pGPIOConfiguration, config.pSPIConfiguration, 0, 16, (uint8_t*) "This is a demo for SSD1306/1106 OLED moudle!", 16, 1);
	ssd1306_refresh_gram(config.pGPIOConfiguration, config.pSPIConfiguration);
	_delay_ms(1000);
	ssd1306_clear_screen(config.pGPIOConfiguration, config.pSPIConfiguration, 0x00);

	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 0, 2, &c_chSingal816[0], 16, 8);
	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 24, 2, &c_chBluetooth88[0], 8, 8);
	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 40, 2, &c_chMsg816[0], 16, 8);
	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 64, 2, &c_chGPRS88[0], 8, 8);
	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 90, 2, &c_chAlarm88[0], 8, 8);
	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 112, 2, &c_chBat816[0], 16, 8);

	ssd1306_draw_3216char(config.pGPIOConfiguration, config.pSPIConfiguration, 0,16, '2');
	ssd1306_draw_3216char(config.pGPIOConfiguration, config.pSPIConfiguration, 16,16, '3');
	ssd1306_draw_3216char(config.pGPIOConfiguration, config.pSPIConfiguration, 32,16, ':');
	ssd1306_draw_3216char(config.pGPIOConfiguration, config.pSPIConfiguration, 48,16, '5');
	ssd1306_draw_3216char(config.pGPIOConfiguration, config.pSPIConfiguration, 64,16, '6');
	ssd1306_draw_1616char(config.pGPIOConfiguration, config.pSPIConfiguration, 80,32, ':');
	ssd1306_draw_1616char(config.pGPIOConfiguration, config.pSPIConfiguration, 96,32, '4');
	ssd1306_draw_1616char(config.pGPIOConfiguration, config.pSPIConfiguration, 112,32, '7');
	ssd1306_draw_bitmap(config.pGPIOConfiguration, config.pSPIConfiguration, 87, 16, &c_chBmp4016[0], 40, 16);

	ssd1306_display_string(config.pGPIOConfiguration, config.pSPIConfiguration, 0, 52, (uint8_t*) "MUSIC", 12, 0);
	ssd1306_display_string(config.pGPIOConfiguration, config.pSPIConfiguration, 52, 52, (uint8_t*) "MENU", 12, 0);
	ssd1306_display_string(config.pGPIOConfiguration, config.pSPIConfiguration, 98, 52, (uint8_t*) "PHONE", 12, 0);

	ssd1306_refresh_gram(config.pGPIOConfiguration, config.pSPIConfiguration);
    /* Loop forever */
	while (1);

	return 0x0;
}
